DEBUG_MODE=1

APP_ROOT_PATH=/home/aarbuzov/work-and-study/git/Wave-U-Net-Pytorch
BATCH_SIZE=4
CHANNELS=1
CHECKPOINT_DIR=${APP_ROOT_PATH}/checkpoints/
CONV_TYPE=gn 
CUDA=1 
CYCLES=2
DATASET_DIR=${APP_ROOT_PATH}/musdb18hq_geant4_2_classes_Eu152_n=720Y/
DEPTH=1 
EXAMPLE_FREQ=3000
FEATURE_GROWTH=double
FEATURES=32 
HDF_DIR=${APP_ROOT_PATH}/hdf/
INSTRUMENTS=1 
KERNEL_SIZE=5 
LEVELS=6
LOAD_MODEL=None
LOG_DIR=${APP_ROOT_PATH}/logs/waveunet/
LOSS=L1
LR=1e-3
MIN_LR=5e-5
NUM_WORKERS=1
OUTPUT_SIZE=1.0 
OUTPUT=None
PATIENCE=2
RES=fixed 
SEPARATE=1 
SR=11025
STRIDES=4

REGISTRY_URI_NAME=sqlite:///mlflow.db
TRACKING_URI_NAME=http://0.0.0.0:5003
EXPERIMENT_NAME=nuclide_separation_models