DEBUG_MODE=1

APP_ROOT_PATH=/home/aarbuzov/work-and-study/git/Wave-U-Net-Pytorch
BATCH_SIZE=4
CHANNELS=1
CONV_TYPE=gn 
CUDA=1 
DEPTH=1 
FEATURE_GROWTH=double
FEATURES=32 
INPUT=${APP_ROOT_PATH}/audio_examples/mixture-noRU106_2_classes_sr11025_n=840/mixture.wav
INSTRUMENTS=1 
KERNEL_SIZE=5 
LEVELS=6 
LOAD_MODEL=${APP_ROOT_PATH}/checkpoints/checkpoint_30200
OUTPUT_SIZE=1.0 
OUTPUT=None
RES=fixed 
SEPARATE=1 
SR=11025
STRIDES=4 
