DEBUG_MODE=1

APP_ROOT_PATH=/home/aarbuzov/work-and-study/git/Wave-U-Net-Pytorch
LOAD_MODEL=${APP_ROOT_PATH}/checkpoint2/checkpoint_30200/
INPUT=${APP_ROOT_PATH}/audio_examples/
CHANNELS=1
SR=11025

INSTRUMENTS=1 
CUDA=1 
FEATURES=1 
BATCH_SIZE=1 
LEVELS=1 
DEPTH=1 
KERNEL_SIZE=1 
OUTPUT_SIZE=1 
STRIDES=1 
CONV_TYPE=1 
RES=1 
SEPARATE=1 
FEATURE_GROWTH=1 
OUTPUT=1 
